### PR TITLE
Implement Offset Commit/Fetch API

### PR DESCRIPTION
**Pull request by gregf1**
Implementation of Offset Commit/Fetch API

### CODE REVIEW

**Comment by vladm** [comment]
Thank you for your pull request. 

Are you going to work on calls related to consumer groups (Group Membership API) as well? It seems isolated implementation of offset commit doesn't make much sense w/o group membership part, as they are needed for Offset Commit/Fetch.

**Comment by gregf1** [comment]
Offset Commit/Fetch works fine using a simple string as the group_id.  This makes it possible to, for example, restart a consumer and have it resume from the same point.  When used with something like Docker and Marathon (which is what I am doing), this patch is sufficient to run consumer groups of a fixed size.

I am also considering the Group Membership API as it would allow us to scale consumer groups up and down.  Time permitting, I may be able to write and submit a pull request for that at some point in the future.

**Comment by vladm** [comment]
Greg, as far as I understand the current implementation doesn't support group management API, if so, could you add a paragraph in "BUGS AND LIMITATIONS" describing current implementation of FETCH / COMMIT and the limitations.

Another question - your implementation of fetch_offsets returns naked response as a hash, which is undocumented. Should not it return just offset instead?

**Comment by asolovey** [comment]
Merged in #32

**Pull request closed without merging**
